apiVersion: v2
name: minio
version: "1.0.0"
appVersion: "1.0.0"
home: https://min.io
description: |
  MinIO is a high-performance, S3 compatible object store, open sourced under GNU AGPLv3 license.
keywords:
  - s3
  - storage
  - minio
sources:
  - https://github.com/minio/minio
type: application
maintainers:
  - name: "Sergio Tocalini"
    email: sergiotocalini@gmail.com
    url: https://sergiotocalini.github.io
