apiVersion: v2
name: corteza
version: "1.0.0"
appVersion: "2023.9.7"
home: https://github.com/cortezaproject/corteza
description: |
  Low-code platform
icon: https://avatars.githubusercontent.com/u/50577806?s=48&v=4
keywords:
  - crm
sources:
  - https://github.com/cortezaproject/corteza
type: application
maintainers:
  - name: "Sergio Tocalini"
    email: sergiotocalini@gmail.com
    url: https://sergiotocalini.github.io
