# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: corteza
replicas: 1
image:
  repository: cortezaproject/corteza
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 80
    protocol: TCP
    
service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

probes:
  enabled: false
  
ingress:
  type: ingress
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # kubernetes.io/tls-acme: "true"
  path: /
  pathType: Prefix
  hosts:
    - localhost
  tls:
    - secretName: corteza-tls
      hosts:
        - localhost

env: {}

configmaps:
  LOG_DEBUG: true
  LOG_LEVEL: 'debug'
  HTTP_WEBAPP_ENABLED: true

# DB_DSN, DOMAIN, HOST, AUTH_BASE_URL, AUTH_EXTERNAL_REDIRECT_URL
secrets: {}

existingSecrets: [] 

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  limits:
    cpu: 40m
    memory: 512Mi
  requests:
    cpu: 20m
    memory: 300Mi

# startupProbe:
#   failureThreshold: 5
#   httpGet:
#     path: /healthcheck
#     port: 80
#     scheme: HTTP
#   initialDelaySeconds: 30
#   periodSeconds: 3
#   successThreshold: 1
#   timeoutSeconds: 1
    
securityContext:
  allowPrivilegeEscalation: false
    
nodeSelector: {}

tolerations: []

affinity: {}
