{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-secrets
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | toYaml | b64enc }}
  {{- end }}
{{- end }}
