---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-guacd-configs
data:
{{- if .Values.guacd.configmaps }}
  {{- range $key, $value := .Values.guacd.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-app-configs
data:
{{- if .Values.app.configmaps }}
  {{- range $key, $value := .Values.app.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
