{{- if .Values.guacd.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-guacd-secrets
data:
  {{- range $key, $val := .Values.guacd.secrets }}
  {{ $key }}: {{ $val | toYaml | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.app.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-app-secrets
data:
  {{- range $key, $val := .Values.app.secrets }}
  {{ $key }}: {{ $val | toYaml | b64enc }}
  {{- end }}
{{- end }}
