---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-worker-configs
data:
{{- if .Values.worker.configmaps }}
  {{- range $key, $value := .Values.worker.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-client-configs
data:
{{- if .Values.client.configmaps }}
  {{- range $key, $value := .Values.client.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-nginx-configs
data:
{{- if .Values.nginx.configmaps }}
  {{- range $key, $value := .Values.nginx.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.nginx.volumes.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-nginx-configs-vol
data:
{{- range $key, $value := .Values.nginx.volumes.configmaps }}
  {{ $key }}: |-
    {{- $value | nindent 4 -}}
{{- end }}
{{- end }}
