{{- if .Values.worker.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-worker-secrets
data:
  {{- range $key, $val := .Values.worker.secrets }}
  {{ $key }}: {{ $val | toYaml | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.client.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-client-secrets
data:
  {{- range $key, $val := .Values.client.secrets }}
  {{ $key }}: {{ $val | toYaml | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.nginx.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-nginx-secrets
data:
  {{- range $key, $val := .Values.nginx.secrets }}
  {{ $key }}: {{ $val | toYaml | b64enc }}
  {{- end }}
{{- end }}
---
{{- if .Values.nginx.volumes.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmproj.fullname" . }}-nginx-secrets-vol
data:
{{- range $key, $value := .Values.nginx.volumes.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
