# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nginx:
  replicas: 1
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: 1.27.1-alpine3.20-slim
  ports:
    - name: nginx
      containerPort: 80
      protocol: TCP
  env: {}
  volumeMounts:
    configmaps: /etc/nginx/templates
  volumes:
    configmaps:
      default.conf.template: |
        map $original_uri $api_uri {
            ~^/api(/.*$) $1;
            default $original_uri;
        }
        
        server {
            listen       80;
            server_name  opnform;
            root         /app/public;
            
            access_log /dev/stdout;
            error_log  /dev/stderr error;
            
            index index.html index.htm index.php;

            location / {
                proxy_http_version 1.1;
                proxy_pass http://client:3000;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
            
            location ~/(api|open|local\/temp|forms\/assets)/ {
                set $original_uri $uri;
                try_files $uri $uri/ /index.php$is_args$args;
            }
            
            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass worker:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                #fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/$fastcgi_script_name;
                fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/public/index.php;
                fastcgi_param REQUEST_URI $api_uri;
            }
        }
        
  secrets: {}
  existingSecrets: []
  resources:
    limits:
      cpu: 40m
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 300Mi
  service:
    annotations: {}
    labels: {}
    ports:
      - port: 80
        name: worker
        targetPort: 80
    type: ClusterIP
  securityContext:
    allowPrivilegeEscalation: false
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  replicas: 1
  image:
    repository: jhumanj/opnform-api
    pullPolicy: IfNotPresent
  ports:
    - name: worker
      containerPort: 9000
      protocol: TCP
  env: {}
  secrets: {}
  existingSecrets: []
  resources:
    limits:
      cpu: 40m
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 300Mi
  service:
    annotations: {}
    labels: {}
    ports:
      - port: 9000
        name: worker
        targetPort: 9000
    type: ClusterIP
  securityContext:
    allowPrivilegeEscalation: false
  nodeSelector: {}
  tolerations: []
  affinity: {}

client:
  replicas: 1
  image:
    repository: jhumanj/opnform-client
    pullPolicy: IfNotPresent
  ports:
    - name: client
      containerPort: 3000
      protocol: TCP
  env:
    NUXT_PUBLIC_APP_URL: /
    NUXT_PUBLIC_API_BASE: /api
    NUXT_PRIVATE_API_BASE: http://worker:9000/api
  secrets: {}
  existingSecrets: []
  resources:
    limits:
      cpu: 40m
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 300Mi
  service:
    annotations: {}
    labels: {}
    ports:
      - port: 3000
        name: ui
        targetPort: 3000
        protocol: TCP
    type: ClusterIP
  securityContext:
    allowPrivilegeEscalation: false        
  nodeSelector: {}
  tolerations: []
  affinity: {}
        
  
ingress:
  type: ingress
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: '1.1'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
  path: /
  pathType: Prefix
  hosts:
    - localhost
  tls:
    - secretName: opnform-tls
      hosts:
        - localhost
