name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          path: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Generate gh-pages branch
        run: |
          WORK_DIR=$(pwd)
          while IFS= read -r dir ; do
             package=$(basename "${dir}")
             if [[ -e "${dir}/Chart.yml" || -e "${dir}/Chart.yaml" ]]; then
                cd "${dir}"
                helm package .
                cd ${WORK_DIR}
             fi
             mkdir -p ./gh-pages/${package}
             cp -rpv ./main/charts/${package}/*.tgz ./gh-pages/${package}
          done < <(find ./main/charts -mindepth 1 -maxdepth 1 -type d -print -prune)
          cp -rpv ./main/LICENSE              ./gh-pages/
          cp -rpv ./main/README.md            ./gh-pages/
          cp -rpv ./main/_config.yml          ./gh-pages/
          cp -rpv ./main/artifacthub-repo.yml ./gh-pages/
          cp -rpv ./main/index.html           ./gh-pages/
          cd ./gh-pages
          helm repo index . --merge index.yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull
          git add .
          git status
          git commit -m "Published by GitHub Actions"
          git push

